### ISSUE TITLE
Fabric 1.18 - Exception ticking world

### ISSUE THREAD

**Issue by bessiq** [CrimsonFluff/Crimson-Chickens#28]
Hi there,

I'm looking forward to meeting your chickens, but unfortunately the game crashes before I get to see one! Here is the crash report:

[crash-2021-12-09_09.33.14-server.txt](https://github.com/CrimsonFluff/Crimson-Chickens/files/7685891/crash-2021-12-09_09.33.14-server.txt)

Let me know if you'd like any other details.

**Comment by CrimsonFluff** [comment]
I have just tested on a server with fresh configs and I dont get a crash

Could you please zip me your `config/crimsonchickens` folder, so I can check the configs

**Comment by bessiq** [comment]
Hey, thanks for responding. I didn't alter the configs either, so my guess is a conflict with another mod. When I get a chance, I'll try to slowly narrow down the mod list to see if I can figure it out. But since it doesn't happen right away, it might take some time. I suppose I could try /summon to force the issue though. I'll report back!

**Comment by bessiq** [comment]
The issue seems to only occur when the Eldritch Mobs mod is enabled (version 1.10.1). There is an Eldritch Mobs blacklist I can add via datapack, so maybe I'll try that. Not sure if that will fix the issue, but worth a shot I suppose. Thanks for your help.

**Comment by CrimsonFluff** [comment]
Thank you for trying to narrow down the problem

I'll try and make time to find out whats happening, its probably a mistake I've made 😢

**Comment by bessiq** [comment]
No worries! Glad to help. Modded Minecraft just be like that sometimes. 🙃

**Comment by TheButterbrotMan** [comment]
Ill have an similar problem. 

https://pastebin.com/sucWQ92b

Server crashes when breeding them.

**Comment by CrimsonFluff** [comment]
So basically we need to narrow down mods that cause the crash issue and try to figure out whats happening.  I've run successful test servers for both fabric 1.18.1 and forge 1.18.1.  Although other mods were installed, none that add/manipulate entities

Pulling mods from both your guys mod packs and testing will be time consuming, which is why I'm asking for help. _You don't have to of course_.

**If you would like to help:**

Basically install a few mods, test the S!*t out of Crimson Chickens, if it breaks then submit the crash log, via PasteBin (its free). If it doesn't break then add a few more mods and try again

Also try to indicate what you were doing at time of crash, breeding, exploring, etc

Here are some dev versions - previous crash logs are invalid because the code base has changed and the error line numbers won't be accurate

Forge 1.16.5 - https://1drv.ms/u/s!ArSGAcC04KWsyxGwHDTzK2G7vC3y?e=c0wV1M
Forge 1.18.1 - https://1drv.ms/u/s!ArSGAcC04KWsyxJfpa_SXlAfjgus?e=47wKbm
Fabric 1.18.1 - https://1drv.ms/u/s!ArSGAcC04KWsyxOk8ks7_w6uwvJU?e=2rA5Yt

I recommend deleting `config/crimsonchickens` folder - as some configs have changed

This is by far my biggest mod and is attracting a lot of attention, and of course I don't want to release an unstable mod

Thank you

**Comment by bessiq** [comment]
Hi,

I tested this again using the 1.0.2 and 1.0.3 versions of your mod in my existing 1.18.1 pack. With CC 1.0.2, the packed crashed immediately, but that could just be random as it doesn't crash or throw errors until one of the chickens tries to spawn. With CC 1.0.3, it didn't crash but it still produced many errors in the log and I was unable to /summon one of your chickens. I deleted configs between attempts.

Crash log from 1.0.2 attempt: [crash-2021-12-29_16.29.16-server.txt](https://github.com/CrimsonFluff/Crimson-Chickens/files/7790775/crash-2021-12-29_16.29.16-server.txt)


I then made another 1.18.1 Fabric profile, with only Eldritch Mobs and Crimson Chickens. With both CC versions, it didn't crash (for the brief amount of time I was in-game), but it also produced the same errors and I could not /summon a chicken, nor did I see any.

latest.log from attempt with only CC 1.0.3 and Eldritch Mobs 1.10.2 installed: https://paste.ee/p/r2JfI

I have not had time to add all these chickens to the Eldritch Mobs blacklist yet, but maybe some of this info is helpful anyway!

**Comment by CrimsonFluff** [comment]
thanks for your effort - but just use the versions of chickens mod that I listed in the previous post - because they are the newest versions I will be posting on curseforge (eventually)
I'll take a look at the errors and eldritch mobs as well, I have a feeling this is going to be very frustrating  😺 

thanks again

**Comment by CrimsonFluff** [comment]
Hello, its me again

https://1drv.ms/u/s!ArSGAcC04KWsyxOk8ks7_w6uwvJU?e=l374bX

please try this...

I know what the error is, but not why its happening

**Comment by bessiq** [comment]
The new file you provided is working! It's in my full modpack, with Eldritch Mobs enabled also. I did /summon_eldritch on some mobs to make sure it was working too - a couple not in the allow list (a vanilla cat and a CC chicken) which failed (as expected), and then a mob in the allow list, which worked.

I even bred some CC chickens and that worked also. (I also discovered Cactus Chickens damage other entities which was hilarious - I guess those can't be bred...safely? lol)

I am not a mod dev, but I am guessing since it appears you are replacing vanilla chickens, and Eldritch Mobs is also trying to modify chickens (among other things), that there was some conflict? But, I took chickens off the EM allow list awhile ago, and CC was still not working, so idk.

Let me know if you want me to try anything else!

**Comment by CrimsonFluff** [comment]
Thank you so much for your help - Cactus/radiation/blaze/snow (not sure if I added snow damage in Fabric version) chickens damage entities, except themselves - so maybe separate them from the others 😉 

I havn't looked at Eldritch mobs so I have no idea what it does or how, so fingers crossed all is good

I'll close the issue for now, if it happens again Ill re-open it
