### ISSUE TITLE
more config

### ISSUE THREAD

**Issue by AlleCraft-alterego** [CrimsonFluff/Crimson-Chickens#33]
can be added a config for disable feather drop from chicken output ? and for change or disable food for breading and for chicken on nest (with item or tag) ?

**Comment by CrimsonFluff** [comment]
1) feather drop - no - I want the player to have to deal with extra drops
2) disable food?  how would the player breed the chickens? - I will NOT add a breeding box like the one from the Roost mod
3) do you mean the name render/item render on the Nest? because that should have a config option to disable that - with Forge its in the `crimsonchickens-client.toml` file - In Fabric its the `crimsonchickens.json" file

**Comment by AlleCraft-alterego** [comment]
1) for modpack maker feather is a extra drop userless, can be add a secondary custom output instead
2) dsable or change food fore breading or food for make resources (for exemple for diamond chicken require diamond essence from mystical agriculture for breading and any forge:rods/wooden for make resources on nest)
3) "incubate" food (in second answer)

**Comment by CrimsonFluff** [comment]
1) there are plenty of mods that force the player to deal with extra drops, loot bags, ftb quests, I wont be changing this - I want the player to work for their resources, not get everything for free - also some mods require feathers, cyclic has a flight wand, mob grinding utils requires feathers for mob crusher - this is up to the player, they can keep or trash them

2) this almost exists already. you can `convert` a chicken by feeding a normal chicken a drop item such as coal, if the coal chicken is enabled - I could add a config option for `conversion item`, then instead of `diamonds` you could feed it `mysticalagriculture:diamond_essence` etc

**Comment by AlleCraft-alterego** [comment]
1) i just asked to put the option to disable it or to change the second output via config not to remove it
2) you can add : 
- conversion item
- breeding item
- food item or remove food item(for generate resources on nest)
3) please make a discord server, is very weird discuss on github xD
