### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ChaengieDC** [CrimsonFluff/Crimson-Chickens#49]
Forge Version: 39.0.79
Mod Version: 1.0.3
It's on a server.

So basically, special chickens do exist on the world, we encountered many of them.
We are 3 who tried to test out this interesting mod, but unfortunately, no matter what or how many we feed them, it just doesn't do anything for some reasons. We don't know if we're missing out on something, or there's just an issue there, that's why I'm making this topic for informations.

We can't change their form, nor they lay anything. Here's a screen of the situation if that can help.

Thanks anyway!
(https://user-images.githubusercontent.com/100733371/156264485-b834a555-b691-4ab9-82d3-78bc7b8a50da.png)

**Comment by CrimsonFluff** [comment]
please run a mod like One probe or Jade.
Jade - https://www.curseforge.com/minecraft/mc-mods/jade
One Probe - https://www.curseforge.com/minecraft/mc-mods/the-one-probe

normal chickens take at least 5 minutes to produce drops
when you breed chickens together they become stronger and the drop time will reduce, down to about 1 minute
there is a configuration file `config/crimsonchickens-common.toml` to disable drops in world - this is because the stasis chamber is meant to be used to gather drops

I have just tested with Forge 39.0.79 on a server with other mods and all seems to work

![2022-03-02_01 40 52](https://user-images.githubusercontent.com/10263667/156278619-a9e79a94-bed0-4d56-a2ec-5c1c73bd29cb.png)
