### ISSUE TITLE
Chickens not spawning 1.18.2

### ISSUE THREAD

**Issue by Chunkimunki** [CrimsonFluff/Crimson-Chickens#52]
Without this basic information your issue will be deleted...

**Basic Mod Information**
Forge Version : 40.0.19

Mod Version 1.18.2 1.0.0
 Client 

Thought that this had sorted itself out but still running into issues. No chickens spawn naturally and none from creative chicken spawn egg. Can still hear them spawn in but nothing else. Removing mod then name tagging chickens has no effect - add Crimson Chickens and they've disappeared when logging back in.

Checked with just this mod only and it works fine - chickens alive ho - must be an incompatibilty with 1 or more of the other mods installed - back to hunting out the culprit - phew.

latest.log  in 2 parts   [Part1](https://pastebin.com/waxbQwBM)
                                  [Part2](https://pastebin.com/8PwPCCxU)
 Many thanks

**Comment by Chunkimunki** [comment]
After a long and winding investigation finally found out that it was totally down to me. At quick glance I assumed the config was the same for both versions. It is not, so copying the custom values from 1 save to the new is the reason the chickens were not spawning - *face palm*

**Comment by CrimsonFluff** [comment]
Unfortunately I did make a breaking change to the config system, I do try to mark the description of the download with "Please delete your old configs"

I didnt think that the config change would produce the results you had, you said you could still hear chickens and stuff, which is why I havnt offered a solution - because I just didnt know what was happening

but thanks for trying to find the solution  😃
